### ISSUE TITLE
how to connect and join an external pc to domain in Scenario 1?

### ISSUE THREAD

**Issue by nicolasd85** [aws-quickstart/quickstart-microsoft-activedirectory#47]
Hi good afternoon.
I have setted up the scenario 1 with the new vpc quickstart.
How can i connect with rdp to my server? I need to setup a rdgateway?
How can i join a windows 10 pro pc to my aws new cloud domain?
I don't find any documentation about this.

Thanks.

**Comment by nicolasd85** [comment]
I'm trying to launch the aws-quickstart for the RDGateway in my new Quickstart domain using this template:

https://github.com/aws-quickstart/quickstart-microsoft-rdgateway/blob/master/templates/rdgw-domain.template

But fails: 

![image](https://user-images.githubusercontent.com/54359525/64118956-222dc680-cd6f-11e9-973c-82f237a364d5.png)


I also don't see errors on Auto-Scaling Groups:

![image](https://user-images.githubusercontent.com/54359525/64118891-fad6f980-cd6e-11e9-91ee-dd13a3d274fd.png)


Here is the  cfn\log:

2019-09-02 13:00:22,032 [DEBUG] Restarting cfn-hup due to change detected in dependency
2019-09-02 13:00:22,313 [INFO] Running config join
2019-09-02 13:00:22,313 [DEBUG] No packages specified
2019-09-02 13:00:22,313 [DEBUG] No groups specified
2019-09-02 13:00:22,313 [DEBUG] No users specified
2019-09-02 13:00:22,313 [DEBUG] No sources specified
2019-09-02 13:00:22,313 [DEBUG] No files specified
2019-09-02 13:00:22,361 [DEBUG] No services specified
2019-09-02 13:00:22,375 [DEBUG] Running command a-join-domain
2019-09-02 13:00:22,375 [DEBUG] No test for command a-join-domain
2019-09-02 13:00:26,875 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2019-09-02 13:00:26,875 [DEBUG] Signaling resource RDGWAutoScalingGroup in stack RD-DOMAINGATEWAY with unique ID i-033f1c81dfd604b1b and status FAILURE
2019-09-02 13:00:27,438 [ERROR] Command a-join-domain (powershell.exe -Command "C:\cfn\scripts\Join-Domain.ps1 -DomainName '***' -UserName 'DC\Admin' -Password '") failed
2019-09-02 13:00:27,438 [DEBUG] Command a-join-domain output: Command failure in Add-Computer C:\cfn\scripts\Join-Domain.ps1 on line 19
Exception: System.InvalidOperationException: Computer EC2AMAZ-FKAP2RT failed to join domain ************** from its
current workgroup WORKGROUP with following error message: T...
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\AWSQuickStart\AWSQuickStart.psm1:314 char:13

        throw $CmdSafeErrorMessage
        ~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : OperationStopped: (Command failure...r message: T...:String) [], RuntimeException
FullyQualifiedErrorId : Command failure in Add-Computer C:\cfn\scripts\Join-Domain.ps1 on line 19
Exception: System.InvalidOperationException: Computer EC2AMAZ-FKAP2RT failed to join domain *********** from
its current workgroup WORKGROUP with following error message: T...
2019-09-02 13:00:27,438 [ERROR] Error encountered during build of join: Command a-join-domain failed
Traceback (most recent call last):
File "cfnbootstrap\construction.pyc", line 544, in run_config
File "cfnbootstrap\construction.pyc", line 138, in run_commands
File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command a-join-domain failed
2019-09-02 13:00:27,438 [ERROR] -----------------------BUILD FAILED!------------------------
2019-09-02 13:00:27,438 [ERROR] Unhandled exception during build: Command a-join-domain failed
Traceback (most recent call last):
File "cfn-init", line 171, in 
File "cfnbootstrap\construction.pyc", line 129, in build
File "cfnbootstrap\construction.pyc", line 530, in build
File "cfnbootstrap\construction.pyc", line 544, in run_config
File "cfnbootstrap\construction.pyc", line 138, in run_commands
File "cfnbootstrap\command_tool.pyc", line 117, in apply
ToolError: Command a-join-domain failed

Can you help me?

Regards!

**Comment by nicolasd85** [comment]
Sorry i realize how to solve it.
It seems that when you create the Domain with the scenario 1 template it ask for two passwords for the admin account.
The remote destkop gateway template doesn't work with the first password. You need to use the secondary password.

BTW i still need help to join windows 10 pro machines that are local in my office.

**Comment by nicolasd85** [comment]
I need to connect with a VPN to my AWS EC2 Domain in this scenario?

**Comment by virtlima** [comment]
Scenario 2 was made for that use case, Scenario 2 which has not been updated basically deploys two ec2 instances not joined to anything, leaving it up to you to join to domain and dc promo etc. Part of the reason is due to DNS Complexity, but we could make DNS Servers a Parameter you can configure.  One thought I had for the update is that unlike Scenario 1 which promotes with the thought of a new Domain, that in scenario 2 we would port all the code but always join the DCs to a domain. The VPN part would still need to be pre-setup...  Would that be helpful to you? Please let us know. Scenario 1 is very much focused on net new Forest, you could do a trust with your existing domain as would be the case in Scenario 3. Hope that makes sense.

**Comment by nicolasd85** [comment]
I want to deploy a new forest and domain in my aws cloud and be able to join computers from my local Office or "anywhere"

**Comment by virtlima** [comment]
Oh okay, so then after deploy you would need to setup some type of connectivity to your VPC, VPN being the quickest option. You then want to ensure that DNS is configured in a way that allows the local Offices or Anywhere to know how to reach the DCs for your domain. So to answer your question yes  you would need to connect VPN to your VPC the DC are in, in Scenario 1. Our [Documentation](https://docs.aws.amazon.com/vpn/latest/s2svpn/SetUpVPNConnections.html) has a getting started guide for Site to Site VPN. This [page](https://docs.aws.amazon.com/vpc/latest/userguide/vpn-connections.html) covers the VPN Options. Hope this helps, please let us know.

**Comment by nicolasd85** [comment]
Hi @virtlima i have another problem with the Scenario-2 Template it's failing in the creation of the RDGWAutoScalingGroup:

![image](https://user-images.githubusercontent.com/54359525/65333317-a7e6aa00-db96-11e9-8ec7-b8ba18ff6644.png)

**Comment by virtlima** [comment]
How many EIPs are allocated in your account? The Default limit is five, the RDGW one consumes two, and if you are deploying our VPC template we deploy two NAT Gateways requiring two EIPs. We have not updated the RDGW Quick Start yet, but its one of the things we are hoping to scope down. In short you may be at your limit of EIPs. Conversely, you would need to disable rollback on failure and then take a look at the logs on one of the deployed RDGW boxes under C:\cfn\log to see what potentially failed.

**Comment by nicolasd85** [comment]
You were right it was the amount of EIPs. I release 1 and it worked.

**Comment by nicolasd85** [comment]
Can you update the stack to use Windows 2019 AMIs instead of 2016?

**Comment by nicolasd85** [comment]
sorry i mean the scenario-2 master stack. it creates win server 2016 amis.

**Comment by virtlima** [comment]
No problem we will get that updated to match the other scenario.

**Comment by nicolasd85** [comment]
Can you let me know when it's done please?

**Comment by virtlima** [comment]
This has been done, note you could also modify yourself if you run the scenario2 template not from the master template. I am going to close this thread out, feel free to open it up with additional questions.

**Comment by nicolasd85** [comment]
@virtlima when you use administrator as admin user the Scenario-2 master stack fails when creates the RDGW AutoScalling Group
